import 'package:flutter/material.dart';
import 'naver_map_screen.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class LoginPage extends StatelessWidget {
  const LoginPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(
          padding: EdgeInsets.all(20),
          children: [
            const GoogleLogin(),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                navigateToNaverMap(context);
              },
              child: const Text('Go to Naver Map'),
            ),
          ],
        ),
      ),
    );
  }

  void navigateToNaverMap(BuildContext context) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => const NaverMapScreen()),
    );
    print("Navigating to Naver Map");
  }
}

class GoogleLogin extends StatelessWidget {
  const GoogleLogin({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(color: const Color(0xFFFAFCFF)),
          child: Column(
            children: [
              const LogoImage(),
              const SizedBox(height: 30),
              const LoginButton(text: '여행계획~', onPressed: null),
              const SizedBox(height: 20),
              const GoogleSignInButton(),
              const SizedBox(height: 20),
              OrContinueWithDivider(),
              const SizedBox(height: 20),
              const LoginButton(
                text: 'Log in',
                color: Color(0xFF0061FF),
                textColor: Colors.white,
                onPressed: null,
              ),
              const SizedBox(height: 20),
              const SignUpPrompt(),
            ],
          ),
        ),
      ],
    );
  }
}

class LogoImage extends StatelessWidget {
  const LogoImage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 299,
      height: 292,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: NetworkImage("https://via.placeholder.com/299x292"),
          fit: BoxFit.fill,
        ),
      ),
    );
  }
}

class GoogleSignInButton extends StatelessWidget {
  const GoogleSignInButton({super.key});

  @override
  Widget build(BuildContext context) {
    return LoginButton(
      text: 'Sign in with Google',
      icon: FlutterLogo(size: 24),
      color: Colors.transparent,
      textColor: const Color(0xFF0061FF),
      borderColor: const Color(0xFF0061FF),
      onPressed: () {
        // Google Sign-in logic
      },
    );
  }
}

class LoginButton extends StatelessWidget {
  final String text;
  final Color color;
  final Color textColor;
  final Color? borderColor;
  final Widget? icon;
  final VoidCallback? onPressed;

  const LoginButton({
    required this.text,
    this.color = Colors.transparent,
    this.textColor = Colors.black,
    this.borderColor,
    this.icon,
    this.onPressed,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 343,
      padding: const EdgeInsets.symmetric(vertical: 12),
      decoration: BoxDecoration(
        color: color,
        borderRadius: BorderRadius.circular(6),
        border: borderColor != null ? Border.all(color: borderColor!) : null,
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          if (icon != null) icon!,
          if (icon != null) const SizedBox(width: 8),
          Text(
            text,
            style: TextStyle(color: textColor, fontSize: 14, fontWeight: FontWeight.w500),
          ),
        ],
      ),
    );
  }
}

class OrContinueWithDivider extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(child: Divider(color: Color(0xFFBAC1CE))),
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 8.0),
          child: Text(
            'Or continue with',
            style: TextStyle(color: Color(0xFFBAC1CE), fontSize: 14),
          ),
        ),
        Expanded(child: Divider(color: Color(0xFFBAC1CE))),
      ],
    );
  }
}

class SignUpPrompt extends StatelessWidget {
  const SignUpPrompt({super.key});

  @override
  Widget build(BuildContext context) {
    return RichText(
      textAlign: TextAlign.center,
      text: TextSpan(
        children: [
          const TextSpan(
            text: 'Don’t have an account? ',
            style: TextStyle(color: Color(0xFF12282A), fontSize: 16),
          ),
          TextSpan(
            text: 'Sign up.',
            style: const TextStyle(
              color: Color(0xFF0061FF),
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }
}
